spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employees
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filters: stat,wall,slf4j
      filter:
        stat:
          enabled: true
        wall:
          enabled: true
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
      web-stat-filter:
        enabled: true
        url-pattern: /*
      aop-patterns: com.springdemo.helloworld.*

  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  jdbc:
    template:
      query-timeout: 3
  redis:
    password: redis
    host: localhost
    port: 6379

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.springdemo.helloworld.domain
  mapper-locations: classpath:mapper/*.xml

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

